namespace APISegaAI.Domain.Entity
{
    /// <summary>
    /// Сущность для хранения тестовых данных (datapool), которые могут быть сгенерированы автоматически или загружены пользователем.
    /// Группирует элементы данных (DataPoolItem) с метаданными, такими как описание и источник генерации.
    /// Может быть связана с TestCase для использования в конкретных тестах.
    /// Обеспечивает управление тестовыми данными, их экспорт в CSV/Excel и интеграцию с процессом генерации тест-кейсов,
    /// снижая трудозатраты на подготовку данных для тестирования.
    /// </summary>
    public class DataPool
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string Id { get; set; } = Guid.NewGuid().ToString(); // Уникальный идентификатор

        [Required]
        [MaxLength(1000)]
        public string Description { get; set; } = string.Empty; // Описание datapool

        [Required]
        public DataPoolSource Source { get; set; } = DataPoolSource.AutoGenerated; // Источник (UserProvided/AutoGenerated)

        public List<DataPoolItem> Items { get; set; } = new List<DataPoolItem>(); // Коллекция элементов данных

        [ForeignKey(nameof(TestCase))]
        public string? TestCaseId { get; set; } // Внешний ключ для связи с TestCase (опционально)

        [JsonIgnore]
        public TestCase? TestCase { get; set; } // Навигационное свойство (опционально)
    }
}