namespace APISegaAI.Domain.Enums
{
    // для указания источника тестовых данных (загружено пользователем или сгенерировано LLM).
    public enum DataPoolSource
    {
        UserProvided,  // Загружено пользователем
        AutoGenerated  // Сгенерировано автоматически
    }
}